### ISSUE TITLE
Upload production Testfight version Fail

### ISSUE THREAD

**Issue by ReginaSun** [distriqt/ANE-LineSDK#3]
##### Expected behaviour
Upload production Testfight version Fail

##### Actual behaviour
Upload production Testfight version Fail

##### Environment 

- AIR SDK version: 32 Beta (windows)
- Device OS: iOS
- Device version: 12.1.2
- Development IDE: flash develop
- Development OS: windows

##### Logs
We package development ver and resign can work fine.

We tried to package Testfight ver and resign was not error, but there were two errors when uploading

Can you help us solve this problem?

![fail](https://user-images.githubusercontent.com/20833433/54251264-a30ac300-4581-11e9-93b1-a93adb68be94.png)

**Comment by marchbold** [comment]
Are you attempting to package your app with bitcode? Could you show me the package command you are using?

**Comment by ReginaSun** [comment]
HI~

This is the package command we use.

call adt -package -target ipa-test-interpreter   -storetype pkcs12 -keystore "cert/iOS/testfly/BonusWinner_MJ16TW.p12" -storepass bonuswinner -provisioning-profile cert/iOS/testfly/tw8com8bonuswinner8mj16tw.mobileprovision "dist\MJ16TW-BW-Apple-TestFight-test-interpreter.ipa" "application_ios_testfight.xml" -C bin . -C "icons/ios" . -C "localgame/ios" . -extdir lib/

**Comment by ReginaSun** [comment]
I~

This is the package command we use.

call adt -package -target ipa-test-interpreter -storetype pkcs12 -keystore "cert/iOS/testfly/BonusWinner_MJ16TW.p12" -storepass xxxxxxxx -provisioning-profile cert/iOS/testfly/tw8com8bonuswinner8mj16tw.mobileprovision "dist\MJ16TW-BW-Apple-TestFight-test-interpreter.ipa" "application_ios_testfight.xml" -C bin . -C "icons/ios" . -C "localgame/ios" . -extdir lib/

**Comment by ReginaSun** [comment]
HI~

This is the package command we use.

call adt -package -target ipa-test-interpreter -storetype pkcs12 -keystore "cert/iOS/testfly/zzzzzz.p12" -storepass xxxxxxxx -provisioning-profile cert/iOS/testfly/tw8com8bonuswinner8mj16tw.mobileprovision "dist\MJ16TW-BW-Apple-TestFight-test-interpreter.ipa" "application_ios_testfight.xml" -C bin . -C "icons/ios" . -C "localgame/ios" . -extdir lib/

**Comment by marchbold** [comment]
What about the distribution version?

**Comment by marchbold** [comment]
Could you try again with the update we are pushing shortly?

**Comment by ReginaSun** [comment]
HI~

We have successfully packaged and uploaded the Testfight version app using the new line sdk.

However, I received a reply from the apple store(Testfight) and told the app that I have an issue and failed the review.

![image](https://user-images.githubusercontent.com/20833433/54337629-72eb1f00-466a-11e9-9021-874b1b7b34c6.png)

**Comment by marchbold** [comment]
That's probably related to an environment or AIR issue. 

What version of AIR are you using and are you packaging on a recent macOS machine ?

**Comment by ReginaSun** [comment]
HI~

We are packaged in air sdk 32 beta(windows ver) on windows 10.

https://labs.adobe.com/downloads/air.html

**Comment by ReginaSun** [comment]
HI~

We are packaged in air sdk 32 beta(windows ver) on windows 10.

https://labs.adobe.com/downloads/air.html

Package(windows)->Resign(macOS)->Upload(macOS)

We perform the macOS as shown below:

<img width="537" alt="螢幕快照 2019-03-15 上午11 39 02" src="https://user-images.githubusercontent.com/20833433/54407548-35919a80-4719-11e9-8167-84a43f6e2468.png">

![image](https://user-images.githubusercontent.com/20833433/54407577-53f79600-4719-11e9-8c51-423ed3e1104c.png)

**Comment by marchbold** [comment]
Can you try to package on macOS, I'm gathering the issue is with the windows packaging.

**Comment by ReginaSun** [comment]
Hi~
We will try it and maybe it will take a lot of time.
Because our work is almost done on windows
Unfamiliar with macOS

**Comment by marchbold** [comment]
How did you go, have you been able to build on macOS?

**Comment by ReginaSun** [comment]
Hi~

We should try to package with the adt in air sdk (macOS)

Since there are other jobs being executed in the past few days, I will start trying to package the app today.

Can you provide documentation about the macOS package?

**Comment by marchbold** [comment]
Do you mean how to use the AIR SDK to package your application? 

Here is a reference on using adt:

https://help.adobe.com/en_US/air/build/WS901d38e593cd1bac35eb7b4e12cddc5fbbb-8000.html

**Comment by ReginaSun** [comment]
Ok~ Thanks. 
I will try it.

**Comment by ReginaSun** [comment]
We tried to package the app in macOS and resign it, but it still can't be displayed in the apple background management interface after uploading.

What should I do next?

This is our package script
[packageapp_sh.zip](https://github.com/distriqt/ANE-LineSDK/files/2990719/packageapp_sh.zip)

**Comment by marchbold** [comment]
What does that mean? I thought the error was with "invalid swift support" when uploading?

**Comment by ReginaSun** [comment]
1.We package and resign app in macOS.

<img width="673" alt="螢幕快照 2019-03-21 下午1 23 01" src="https://user-images.githubusercontent.com/20833433/54735551-d2ed4280-4be1-11e9-8dd5-763c2533074f.png">

2.We use the Application Loader to upload the app(ver 2.30.79).

<img width="802" alt="螢幕快照 2019-03-21 下午1 25 06" src="https://user-images.githubusercontent.com/20833433/54735624-311a2580-4be2-11e9-80cb-5ba1d4a61c79.png">
<img width="703" alt="螢幕快照 2019-03-21 下午1 25 34" src="https://user-images.githubusercontent.com/20833433/54735630-39726080-4be2-11e9-99bc-cacd186ccb48.png">
<img width="700" alt="螢幕快照 2019-03-21 下午1 28 21" src="https://user-images.githubusercontent.com/20833433/54735640-442cf580-4be2-11e9-8f32-f9cba8541096.png">

3.But the interface of app store connect does not show this version of the app(ver 2.30.79).

![APP1](https://user-images.githubusercontent.com/20833433/54735670-776f8480-4be2-11e9-85bb-8d9af92686f2.png)
![APP2](https://user-images.githubusercontent.com/20833433/54735675-7dfdfc00-4be2-11e9-8266-b6b83d2fae74.png)

What should I do next or is there anything wrong with my steps?


----------------------------  **If the package does not contain LineSdk and frameworks folders**

1.We package the app(ver 2.30.80) and don't include the LineSdk and frameworks folder in macOS.

2.We use the Application Loader to upload the app(ver 2.30.80).

<img width="700" alt="螢幕快照 2019-03-21 下午1 52 06" src="https://user-images.githubusercontent.com/20833433/54735930-a76b5780-4be3-11e9-9412-11cdcf4b9e8f.png">
<img width="702" alt="螢幕快照 2019-03-21 下午1 54 22" src="https://user-images.githubusercontent.com/20833433/54735939-b0f4bf80-4be3-11e9-9522-c91d4f4eb112.png">

3.Then the interface of app store connect will show the app(ver 2.30.80) which has just been uploaded.

![APP3](https://user-images.githubusercontent.com/20833433/54736098-80615580-4be4-11e9-865e-98e831925873.png)
![APP4](https://user-images.githubusercontent.com/20833433/54736099-80615580-4be4-11e9-8d26-1c7d05286f8c.png)

4.Then we can test on testfight.

**Comment by marchbold** [comment]
You should be packaging for ipa-app-store not ipa-test-interpreter. That is only for debug builds.

**Comment by ReginaSun** [comment]
Ok, I will try it.
Thank you.

**Comment by ReginaSun** [comment]
We have completed the testfight version test with Line sdk.
It works fine.

**Comment by marchbold** [comment]
Excellent! Thanks for letting us know.
