### ISSUE TITLE
LineSDK Android 64bit update

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-LineSDK#5]
Update the extension to include support for Android 64bit

>
> Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures. 64-bit CPUs deliver faster, richer experiences for your users. Adding a 64-bit version of your app provides performance improvements, makes way for future innovation, and sets you up for devices with 64-bit-only hardware.
>

**Comment by marchbold** [comment]
Beta: https://www.dropbox.com/sh/fje7bk3hzddal5x/AABPhmNqwW5ISFpdHgJLklN1a?dl=0

**Comment by ReginaSun** [comment]
Hi:

Line SDK 64bit is OK.

Thank you for your support.

**Comment by marchbold** [comment]
Thanks for the feedback, we will push this into release shortly but the above version will be fine for release builds.

**Comment by ReginaSun** [comment]
OK.
Thank you. :)
