### ISSUE TITLE
AndroidX update

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-LineSDK#6]

**Comment by ReginaSun** [comment]
It’s been a while since our last contact. We have a request for Distriqt.

We want to ask you to update the Line SDK support Android X.

Will Distriqt need to send us a quote on this update?

If so, please do so as soon as reasonably possible.

Thank you.

**Comment by marchbold** [comment]
Apologies, I just saw this. I've responded to your email, let me know if you have any questions.

**Comment by YenZtudio** [comment]
Hello, hope to get update for Android X support too
