### ISSUE TITLE
Line ANE v3.0 crashes on iOS 13.4.1

### ISSUE THREAD

**Issue by YenZtudio** [distriqt/ANE-LineSDK#7]
##### Expected behaviour
Launch app

##### Actual behaviour
App crash since start

##### Environment 

- AIR SDK version: 33.1.1.98
- Device OS:  13.4.1
- ANE Version v3.0
(ANE version v1.0 is latested worked, it can launch app but random crash when login Line)

**Comment by ReginaSun** [comment]
Hi

Environment
AIR SDK version: 33.1.1.98
Device OS: 13.4.1
ANE Version v3.0

On the ios 13.4.1, we have found the same issue.

App that was previously authorized by Line and successfully logged in, it works fine.

However, when the app is not authorized by Line, it will crash when the authorization is successful and the login is performed.

Can you help us confirm this issue and provide an improvement plan?

Also want to ask if Line SDK ANE contains UIWebview?

If there is, we hope to remove it so that we can submit the review without warning message.

If the above solution requires additional payment, please mail to Gaby.

Thanks.

ps: attach crash log
[Crash Log.txt](https://github.com/distriqt/ANE-LineSDK/files/4661182/Crash.Log.txt)

**Comment by ReginaSun** [comment]
Hi

Environment
AIR SDK version: 33.1.1.98
Device OS: 13.4.1 (Only happens after iOS 13.4)
ANE Version: v3.1.073

The app will still crash.

When the app contains the Line sdk and re-sign, the Facebook API will also crash after logging in.

The same crash situation as the Line sdk occurs when the login completion callback app.

If the app does not contains the Line sdk and re-sign, the Facebook API can work fine.


My packaged app is a test version.

ex:
call adt -package -target ipa-test-interpreter  -storetype pkcs12 -keystore "cert/iOS/test/xxxxx.p12" -storepass xxxxx -provisioning-profile cert/iOS/test/xxxxxxxxx.mobileprovision  "dist\BWLobby-BW-Apple-Test.ipa" "application_ios_test.xml"  -C bin . -C "icons/ios" . -C "External/ios" . -extdir lib/common/ -extdir "lib/ios/" -extdir "lib/common_platform/"


my app.xml

	<extensions>
		<extensionID>com.bonuswinner.getipv6</extensionID>
		<extensionID>com.freshplanet.ane.AirDeviceId</extensionID>	
        	<extensionID>com.distriqt.Core</extensionID>
		<extensionID>com.distriqt.Bolts</extensionID>
		<extensionID>com.distriqt.playservices.Base</extensionID>		
		<extensionID>com.distriqt.NativeWebView</extensionID>
		<extensionID>com.distriqt.LineSDK</extensionID>
		<extensionID>com.distriqt.NetworkInfo</extensionID>
		<extensionID>com.distriqt.Application</extensionID>	
		<extensionID>com.distriqt.PushNotifications</extensionID>
		<extensionID>com.distriqt.Firebase</extensionID>
		<extensionID>com.google.firebase.core</extensionID>		
		<extensionID>com.distriqt.Message</extensionID>	
		<extensionID>com.distriqt.Vibration</extensionID>
		<extensionID>com.distriqt.Dialog</extensionID>
		<extensionID>com.distriqt.ApplicationRater</extensionID>
		<extensionID>com.distriqt.FacebookAPI</extensionID>
		<extensionID>com.distriqt.playservices.Auth</extensionID>		
		<extensionID>com.distriqt.InAppBilling</extensionID>
		<extensionID>com.distriqt.ZipUtils</extensionID>
		<extensionID>com.distriqt.Volume</extensionID>		
	</extensions>

Can you help us confirm this issue and provide an improvement plan?

Thanks.

ps: attach crash log
[LineSDK Crash Log.txt](https://github.com/distriqt/ANE-LineSDK/files/4721971/LineSDK.Crash.Log.txt)

**Comment by marchbold** [comment]
Just checking in an update now, could you confirm this fixes the issue for you?
Cheers

**Comment by ReginaSun** [comment]
OK. Thanks for your support.

**Comment by ReginaSun** [comment]
We conducted some tests and it works fine.

This issue was successfully fixed.

Thanks for your support.

**Comment by marchbold** [comment]
Thanks for the feedback.
